name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          # Создаем файл с ключом
          echo "${{ secrets.OKNAMOBIFON_NEW_KEY }}" > key
          chmod 600 key
          
          # Проверяем ключ
          echo "=== Key info ==="
          ssh-keygen -l -f key
          
          # Добавляем сервер в known_hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.OKNAMOBIFON_HOST }} >> ~/.ssh/known_hosts
          
          # Пробуем простое подключение
          echo "=== Testing connection ==="
          ssh -v -i key ${{ secrets.OKNAMOBIFON_USERNAME }}@${{ secrets.OKNAMOBIFON_HOST }} "echo 'Test successful'" || echo "Connection failed"

      - name: Deploy application
        run: |
          ssh -i key ${{ secrets.OKNAMOBIFON_USERNAME }}@${{ secrets.OKNAMOBIFON_HOST }} "
            cd /var/www/u1079678/data/www/oknamobifon.ru/wp-content/themes/oknamobifon/promo
            if [ -d .git ]; then
              git pull origin main
            else
              rm -rf *
              git clone https://github.com/site100ru/oknamobifon-promo.git .
            fi
          "
          rm -f key 