name: Deploy oknamobifon-promo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH connection
          run: |
            # Сохраняем ключ из секрета во временный файл
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/debug_key
            chmod 600 /tmp/debug_key
            
            # Проверяем содержимое ключа
            echo "=== Key content (first 100 chars) ==="
            head -c 100 /tmp/debug_key
            echo -e "\n\n=== Key content (last 100 chars) ==="
            tail -c 100 /tmp/debug_key
            echo -e "\n"
            
            # Проверяем формат ключа
            echo "=== Key format check ==="
            ssh-keygen -l -f /tmp/debug_key || echo "Key format is invalid!"
            
            # Пробуем подключиться с максимально подробным выводом
            echo "=== Trying connection ==="
            ssh -vvv -i /tmp/debug_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SUCCESS'" || echo "CONNECTION FAILED"
            
            # Убираем за собой
            rm -f /tmp/debug_key
