name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and deploy
        run: |
          # Создаем файл с ключом
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key
          chmod 600 key
          
          # Добавляем сервер в known_hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          # Выполняем команды на сервере
          ssh -o StrictHostKeyChecking=no -i key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd /var/www/u1079678/data/www/oknamobifon.ru/wp-content/themes/oknamobifon/promo
            if [ -d .git ]; then
              echo 'Updating existing repository...'
              git pull origin main
            else
              echo 'Cloning new repository...'
              rm -rf *
              git clone https://github.com/site100ru/oknamobifon-promo.git .
            fi
            echo 'Deployment completed successfully!'
          "
          
          # Очищаем ключ
          rm -f key
